name: build_and_push

on: push

jobs:
  deploy:
    runs-on: ubuntu-20.04
    env:
      PUSH_IMG_USER: Kazuki0902Fw
      WORKING_DIR: /srv
      DEST_REPOSITORY: Kazuki0902Fw/g-actions-test-products
    
    steps: 
      - name: set git credential
        run: |
          git remote set-url origin https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}

      - name: checkout source repo
        uses: actions/checkout@v2
      
      - name: extract source repo branch name
        shell: bash
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
        id: extract_branch

      - name: pwd
        run: pwd
      
      - name: build app
        run: make app

      - name: checkout dest repo
        uses: actions/checkout@v2
        with: 
          repository: ${{ env.DEST_REPOSITORY }}
          path: dest
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: pwd
        run: pwd

      - name: cp build
        run: |
          cp -r -f build/app dest

      - name: push to remote
        env:
          BRANCH_NAME: ${{ steps.extract_branch.outputs.branch }}
        run: |
          cd ./dest
          git branch $BRANCH_NAME
          git push origin $BRANCH_NAME

        