name: deploy

on: 
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-20.04
    env:
      PUSH_IMG_USER: Kazuki0902Fw
    
    steps: 
      - name: checkout
        uses: actions/checkout@v2

      
      - name: Extract branch name
        shell: bash
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
        id: extract_branch
      
      - name: build app
        run: make app

      - name: build image
        run: make image

      - name: login ghcr
        run: echo ${{secrets.GITHUB_TOKEN}}  | docker login ghcr.io -u $PUSH_IMG_USER --password-stdin
        
      - name: lowercase user name
        id:   lowercase_user_name
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${PUSH_IMG_USER}

      - name: push image
        env:
          BRANCH_NAME: ${{ steps.extract_branch.outputs.branch }}
          RPO_USER_NAME: ${{ steps.lowercase_user_name.outputs.lowercase }}
        run: |
          docker tag g-actions-test ghcr.io/$RPO_USER_NAME/gactionstest/gactionstest:${BRANCH_NAME}
          docker push ghcr.io/$RPO_USER_NAME/gactionstest/gactionstest:${BRANCH_NAME}
        
        
