name: generate_and_push

on: push

jobs:
  deploy:
    runs-on: ubuntu-20.04
    env:
      DEST_REPOSITORY: Kazuki0902Fw/g-actions-test-products
      GENERATE_FILES_CMD: make app
      GENERATED_DIR: build/app
      COPY_DEST_DIR: dest
    
    steps: 
      - name: extract source repo branch name
        shell: bash
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
        id: extract_branch

      - name: checkout source repo
        uses: actions/checkout@v2
    
      - name: generate files
        run: $GENERATE_FILES_CMD

      - name: checkout dest repo
        uses: actions/checkout@v2
        with: 
          repository: ${{ env.DEST_REPOSITORY }}
          path: dest
          token: ${{ secrets.PAT }}

      - name: cp build
        run: |
          cp -r -f $GENERATED_DIR $COPY_DEST_DIR

      - name: push to remote
        env:
          BRANCH_NAME: ${{ steps.extract_branch.outputs.branch }}
          REMOTE_REPO: "https://${{ secrets.PAT }}:x-oauth-basic@github.com/${{ env.DEST_REPOSITORY }}.git"
        run: |
          cd ./dest
          git pull $REMOTE_REPO
          git config --local user.name "github-actions[bot]" 
          git add -A
          git commit -m "generated files by $GITHUB_REPOSITORY 's commit $GITHUB_SHA "
          git branch $BRANCH_NAME
          git push $REMOTE_REPO $BRANCH_NAME

        