# このworkflowは特定の
name: generate_and_push

on: 
  push:
    paths:
    # 以下の表現にマッチするファイルの変更がpushされた時のみjobが実行される
    # ref: https://docs.github.com/ja/actions/reference/workflow-syntax-for-github-actions#patterns-to-match-branches-and-tags
    - 'app/**/**.go' 

jobs:

  generate_and_push:
    runs-on: ubuntu-20.04
    env:
      DEST_REPOSITORY: Kazuki0902Fw/g-actions-test-products # 生成物をpushするrepository
      PATH_TO_DEST_REPO: ./dest                             # cloneしてきたDEST_REPOSITORYの配置場所
      GENERATE_FILES_CMD: make app                          # ファイル生成するためにsource repositoryで実行する必要があるコマンド
      COPY_FILES_CMD: cp -rf build/app $PATH_TO_DEST_REPO   # 生成したファイルをコピーするコマンド
    
    steps: 
      - name: checkout source repo
        uses: actions/checkout@v2

      - id: extract_branch
        name: extract source repo branch name
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"

      - name: set deploy key for dest repo
        env: 
          DEST_REPOSITORY_DEPLOY_KEY: ${{ secrets.DEST_REPOSITORY_DEPLOY_KEY }}
        run: |
          echo "$DEST_REPOSITORY_DEPLOY_KEY" > ~/id_rsa
          chmod 0600 ~/id_rsa

      - name: clone dest repo
        env: 
          GIT_SSH_COMMAND: ssh -i ~/id_rsa
        run: git clone git@github.com:$DEST_REPOSITORY.git dest

      - name: checkout dest repo branch
        env:
          BRANCH_NAME: ${{ steps.extract_branch.outputs.branch }}
        run: |
          cd $PATH_TO_DEST_REPO 
          git checkout -b $BRANCH_NAME

      - id: check_dest_repo_remote_branch_exists
        name: check remote branch exists in dest repo
        env:
          BRANCH_NAME: ${{ steps.extract_branch.outputs.branch }}
        run: |
          cd $PATH_TO_DEST_REPO 
          branches=$(git ls-remote --heads origin $BRANCH_NAME)
          branches="${branches//$'\n'/\\n}"
          echo "::set-output name=exists::$branches"

      - name: pull dest repo remote branch if needs
        env:
          BRANCH_NAME: ${{ steps.extract_branch.outputs.branch }}
          GIT_SSH_COMMAND: ssh -i ~/id_rsa
        if: steps.check_dest_repo_remote_branch_exists.outputs.exists
        run: |
          cd $PATH_TO_DEST_REPO 
          git pull origin $BRANCH_NAME

      - name: generate and copy files
        run: | 
          $GENERATE_FILES_CMD
          $COPY_FILES_CMD

      - name: push to remote
        env:
          BRANCH_NAME: ${{ steps.extract_branch.outputs.branch }}
          GIT_SSH_COMMAND: ssh -i ~/id_rsa
        run: |
          cd $PATH_TO_DEST_REPO 
          git config --local user.name "github-actions[bot]" 
          git config --local user.email "github-actions[bot]" 
          git add -A
          git commit -m "add generated files by $GITHUB_REPOSITORY 's github actions triggered by pushing commit $GITHUB_SHA "
          git branch
          git push origin $BRANCH_NAME

      - name: cleanup
        if: always()
        run: |
          sudo rm -f ~/id_rsa
          sudo rm -Rf *
        