# このworkflowは特定の
name: generate_and_push

on: 
  push:
    paths:
    # 以下の表現にマッチするファイルの変更がpushされた時のみjobが実行される
    # ref: https://docs.github.com/ja/actions/reference/workflow-syntax-for-github-actions#patterns-to-match-branches-and-tags
    - 'app/**/**.go' 

jobs:

  deploy:
    runs-on: ubuntu-20.04
    env:
      DEST_REPOSITORY: Kazuki0902Fw/g-actions-test-products # 生成物をpushするrepository
      GENERATE_FILES_CMD: make app # ファイル生成するためにsource repositoryで実行する必要があるコマンド
      GENERATED_PATH: ./build/app # 生成物の配置場所
      COPY_DEST_DIR: dest         # 生成物のコピー先
    
    steps: 
      - name: checkout source repo
        uses: actions/checkout@v2

      - name: extract source repo branch name
        id: extract_branch
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"

      - name: set deploy key for dest repo
        env: 
          DEST_REPOSITORY_DEPLOY_KEY: ${{ secrets.DEST_REPOSITORY_DEPLOY_KEY }}
        run: |
          echo $DEST_REPOSITORY_DEPLOY_KEY > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: clone dest repo
        run: git clone git@github.com:$DEST_REPOSITORY.git dest

      - name: checkout dest repo branch
        env:
          BRANCH_NAME: ${{ steps.extract_branch.outputs.branch }}
        run: |
          cd ./dest 
          git checkout -b $BRANCH_NAME

      - name: check remote branch exists
        id: check_remote_branch_exists
        env:
          BRANCH_NAME: ${{ steps.extract_branch.outputs.branch }}
        run: echo "::set-output name=exists::git ls-remote --heads origin $BRANCH_NAME}"
      
      - name: pull dest repo remote branch if needs
        env:
          BRANCH_NAME: ${{ steps.extract_branch.outputs.branch }}
        if: steps.check_remote_branch_exists.exists
        run: |
          cd ./dest
          git pull origin $BRANCH_NAME

      - name: generate files
        run: $GENERATE_FILES_CMD

      - name: cp generate files
        run: |
          cp -r -f $GENERATED_PATH $COPY_DEST_DIR

      - name: push to remote
        env:
          BRANCH_NAME: ${{ steps.extract_branch.outputs.branch }}
        run: |
          cd ./dest 
          git config --local user.name "github-actions[bot]" 
          git config --local user.email "github-actions[bot]" 
          git add -A
          git commit -m "add generated files by $GITHUB_REPOSITORY 's github actions triggered by pushing commit $GITHUB_SHA "
          git branch
          git push origin $BRANCH_NAME

        